### ISSUE TITLE
Use TransactionScope on producer

### ISSUE THREAD

**Issue by mannaro79** [Farfetch/kafka-flow#115]
Hi,
I used one producer, but send message for more topics.
Is possible use TransactionScope for grouping multi send (IProducerAccessor.Produce(...))?

example:
1. open transaction scope
2. read data from db
3. write data on db
4. produce async on topic 1: IProducerAccessor.Produce("topic 1")
5. produce async on topic 2: IProducerAccessor.Produce("topic 2")
6. produce async on topic 3: IProducerAccessor.Produce("topic 3")
7. .................................................
8. if not error transation complete

**Comment by filipeesch** [comment]
Hi @mannaro79 

For now, KafkaFlow does not support transactions, and I think the transaction concept in Kafka is a little different from a database transaction.

In your use case, you can call ProduceAsync(), store the resulting Tasks inside a List and await them with Task.WhenAll(). If one ProduceAsync() call fails, an exception will be thrown and you can rollback your database transaction. This solution is not 100% resilient but will cover most of the failures.
