### ISSUE TITLE
Create a BatchConsumeMiddleware

### ISSUE THREAD

**Issue by filipeesch** [Farfetch/kafka-flow#121]
Today every message is delivered one by one in the middlewares, but sometimes it would be better to process them in batches, some databases or applications work better using batches.

The idea is to accumulate a number of messages or wait some time to build a collection of messages and deliver them to the next middleware to be processed, as it was just one message. The messages offset will be committed only when the entire batch will be processed.

**Comment by douglasg14b** [comment]
@filipeesch Should your middleware be added to the middlewares docs as an item? Might make it more discoverable, I only found it by searching github issues.

**Comment by gsferreira** [comment]
Excellent suggestion @douglasg14b! I will take care of that.
#357
