### ISSUE TITLE
Difficulty with Admin / Admin.WebApi

### ISSUE THREAD

**Issue by mightymiracleman** [Farfetch/kafka-flow#128]
Hello, 

I am very new to Kafka and trying to implement a simple consumer with your library (and btw, this is the best one I've seen so far for dotnet so kudos and thanks!).   I'm able to get my consumer up and running, and it is consuming messages; however, when I issue admin rest requests through swagger for `reset-offsets`  I continually receive:

```
KafkaFlow: Error executing consumer | Data: {"Message":{"ConsumerName":"mastery-commissions"},"Topic":"kafka-flow.admin","PartitionKey":"M2I3Yjg3ZDQtMzFmMy00ZGJhLTk4MjYtYTAwNmI0NTM2NDdm","ConsumerName":"5cc8c82c-a8ed-4603-abd3-617e4bbabfec"} | Exception: {"Type":"System.ObjectDisposedException","Message":"The CancellationTokenSource has been disposed.","StackTrace":"   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()\n   at System.Threading.CancellationTokenSource.Cancel()\n   at KafkaFlow.Consumers.WorkerPoolFeeder.StopAsync()\n   at KafkaFlow.Consumers.MessageConsumer.OverrideOffsetsAndRestartAsync(IReadOnlyCollection\u00601 offsets)\n   at KafkaFlow.TypedHandler.TypedHandlerMiddleware.Invoke(IMessageContext context, MiddlewareDelegate next)\n   at KafkaFlow.Consumers.ConsumerWorker.\u003CStartAsync\u003Eb__13_0()"}
```

I've went back through the docs a few times and I'm not seeing what I have missing here.  I created the "kafka-flow.admin" topic in my local kafka instance, but no dice.  Pause, Resume, Restart seem to work just fine until I issue a reset-offsets; do you have any ideas on what I could be doing wrong?  Much thanks in advance.

**Comment by filipeesch** [comment]
Hi @mightymiracleman, thank you for your feedback :)

We will release a fix for this issue very soon.
