### ISSUE TITLE
Referenced schemas: multiple event types in the same topic using ApacheAvroMessageSerializer

### ISSUE THREAD

**Issue by fab60** [Farfetch/kafka-flow#135]
Hi there,

we are currently evaluating kafka-flow in a scenario where multiple event types are published with Avro serialization and with a schema that's already properly defined in the schema registry. To achieve a bounded set of schemas associated with a topic we are trying to use the schema reference support that has been added since kafka 5.5.0 (https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#referenced-schemas).

Since the AvroSerializerConfig is not directly exposing the "use.latest.version" property we tried imposing the configuration inside the producer config but apparently with no success.

What we are experiencing is that the publish is failing after a subject lookup failure on the schema registry. Apparently the software is still trying to create a new subject by priorly removing a subject with the conventional [topic-name]-value scheme.

The exception captured on the schema registry is quite revealing: 
"POST /subjects/**-value**?deleted=False HTTP/1.1" 404 60  29 (io.confluent.rest-utils.requests)
[2021-04-08 10:51:21,970] INFO Deleting subject -value (io.confluent.kafka.schemaregistry.rest.resources.SubjectsResource)
[2021-04-08 10:51:21,971] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper)
io.confluent.rest.exceptions.RestNotFoundException: Subject '-value' not found.

As you can see the subject name composed is incorrectly "-value": the topic name "topic1" is missing

Overall, the behaviour expected is to access an existing subject by using the topic strategy and to select the latest schema version of the record value being published.

Our environment is:

1. Schema registry: 6.1.1
2. kafka-flow: 1.5.2

Here is the relevant producer configuration:

```
.AddProducer("domain-event-union.publisher", producer => producer
       .DefaultTopic("topic1")
       .WithAcks(KafkaFlow.Acks.All)
       .WithProducerConfig(new ProducerConfig(new Dictionary<string, string> { ["use.latest.version"] = "true" }))
       .AddMiddlewares(middlewares => middlewares
           .AddSerializer(resolver => new ApacheAvroMessageSerializer(resolver,
                new AvroSerializerConfig
                {
                    AutoRegisterSchemas = false,
                    SubjectNameStrategy = SubjectNameStrategy.Topic
                }))))
```

Thank you very much for your time,
Imerio

**Comment by dougolima** [comment]
Hi @fab60 
This configuration should be done in AvroSerializerConfig, like this:

```csharp
var config = new AvroSerializerConfig
{
    AutoRegisterSchemas = false,
    SubjectNameStrategy = SubjectNameStrategy.Topic,
};
// HERE
config.Set("avro.serializer.use.latest.version", "true");

...
.AddProducer("domain-event-union.publisher", producer => producer
        ...
       .AddMiddlewares(middlewares => middlewares
           .AddSerializer(resolver => new ApacheAvroMessageSerializer(resolver,config))))
```
However,  Confluent AvroSerializer doesn't accept any configuration other than those that are exposed:

[here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/AvroSerializer.cs) at line 100

```csharp
foreach (var property in avroConfig)
{
    if (property.Key != AvroSerializerConfig.PropertyNames.AutoRegisterSchemas &&
        property.Key != AvroSerializerConfig.PropertyNames.BufferBytes &&
        property.Key != AvroSerializerConfig.PropertyNames.SubjectNameStrategy)
    {
        throw new ArgumentException($"AvroSerializer: unknown configuration property {property.Key}");
    }
}
```

If I undestood correctly, you are trying to publish different type messages in the same topic, it it right?

If yes, why do not use SubjectNameStrategy.Record like exposed [here ](https://github.com/Farfetch/kafka-flow/blob/master/samples/KafkaFlow.Sample.Avro/Program.cs)?

**Comment by fab60** [comment]
Hi @dougolima,

thank you again for troubleshooting our issue. Our aim is to use the schema references feature to define a controlled "bounded" set of shemas in a scenario where we combine multiple event types in the same topic. As you stated correctly you can achieve a somewhat similar solution by using the record subject name strategy, however without a controlled bounded set of schemas as steated [here](https://docs.confluent.io/platform/current/schema-registry/serdes-develop/serdes-avro.html#multiple-event-types-same-topic-avro) or [more generally here](https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/?_ga=2.193951149.1454059732.1618075506-1487236112.1614329637&_gac=1.251473202.1614329764.EAIaIQobChMIrLruvpaH7wIVFuR3Ch0gfwlCEAAYASAAEgKaMvD_BwE) 
 
It does seem to be a current limitation of the confluent-kafka-dotnet/AvroSerializer: there is no actual support for schema references. Interestingly there was a recent update to include schema registry support for jsonsr and protobuf serde and by examining the [sources](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Protobuf/ProtobufSerializer.cs) of the protobuf serializer they seems to have a far more complete implementation compared with the avro one.

As I understand kafka-flow Protobuf serializer is not yet fully integrated with the schema registry. Do you have a plan for it?
Time permitting, will you accept a contribution?

Regards,
Imerio

**Comment by dougolima** [comment]
@fab60 

If you open a PR related to this, please link with [this issue](https://github.com/Farfetch/kafka-flow/issues/138).

Please let me know if you have any other questions.

Regards,
