### ISSUE TITLE
Producer transaction support

### ISSUE THREAD

**Issue by fab60** [Farfetch/kafka-flow#144]
Hi there,

currently KafkaFlow isn't surfacing pruducer transaction API that are available con the confluent dotnet [consumer](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IProducer.cs).
Is there any plan to support it?

Thanks,
Imerio

**Comment by fab60** [comment]
Examined the [IMessageProducer](https://github.com/Farfetch/kafka-flow/blob/master/src/KafkaFlow/Producers/IMessageProducer.cs) interface and their actual implementations. It seems quite a straightforward task to extended it in order to cover the transaction support that has been added to the [confluent dotnet producer](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/IProducer.cs).

Our main usage scenario is to accomplish "effectively once" semantics on a consumer/producer handler we are corrently implementing using kafka-flow. 

I will try with some experimentation on it before eventually submitting a PR.

**Comment by filipeesch** [comment]
It will be a nice feature @fab60 
Just take a look if we should change something on the consumers' side.

I'll ask you to create your branch from v2 branch e open the PR targeting it too.

**Comment by kosa-gyula-77** [comment]
Hi, I'm wondering what is the plan regarding supporting transactions, please? As far as I see the pull request has not been merged.
I can try getting access to the underlying IProducer instance by adding a ProducerCustomFactory, but this is more like a workaround that I would like to avoid.
Thanks!
