### ISSUE TITLE
IMessageConsumer no longer has Consume property

### ISSUE THREAD

**Issue by paul-green** [Farfetch/kafka-flow#173]
Commit 259dad02a6a9a9b431340242b500c93daf0e0348 still had Consume property, but commit f7bb42963b9490b8384efcc36cb6e7d0a6dd08bc removed it.

I require low level access to the byte[] of the message and was using Consumer.Consume() to get this.

Is there another way (without using typed handlers)?

**Comment by dougolima** [comment]
Hi @paul-green,

You can create a middleware to access the message as byte[]. 

In the [integration tests](https://github.com/Farfetch/kafka-flow/tree/master/src/KafkaFlow.IntegrationTests) there is a sample of this using a middleware called [GzipMiddleware](https://github.com/Farfetch/kafka-flow/blob/master/src/KafkaFlow.IntegrationTests/Core/Middlewares/GzipMiddleware.cs) and the configuration is [here](https://github.com/Farfetch/kafka-flow/blob/master/src/KafkaFlow.IntegrationTests/Core/Bootstrapper.cs) at line 193.

**Comment by filipeesch** [comment]
Hi @paul-green

As Douglas said, you can use a middleware. If did not use any transform middleware (serializer, compressor ... ) the Message property on the MessageCOntext is the raw message, the byte[].

Using the Consume() as you were using will read the next message, losing the current one consumed by KafkaFlow. We encapsulate the real Consumer to avoid this kind of problem 😃
