### ISSUE TITLE
This library is awesome! But config function look horrible!

### ISSUE THREAD

**Issue by QuanJingHong** [Farfetch/kafka-flow#205]
All things in the title. Hope you improve it.

**Comment by filipeesch** [comment]
Thanks and... sorry?
Do you have any suggestions on how to improve?

**Comment by QuanJingHong** [comment]
I only use this library as a code learning, but from the view of a WEB programmer, I want to set the address configuration, default values ...etc in the JSON file. For interfaces, classes that handle logic, I will add it through extension methods.

**Comment by GodSpeedXI** [comment]
I think this is an example. It quite a lot but I like that.

https://github.com/serilog/serilog-settings-configuration

**Comment by filipeesch** [comment]
I understand your point.

We prefer to use C# code to build the configurations to help the client when writing it. With C# we have the IntelliSense and summary descriptions to guide the user. If you write something wrong, the IDE will notify you at compile time.

I know that we can have some of these features with JSON too, creating a schema, but with C# we have more control and more features. A lot of frameworks left behind config files to use a Fluent style configuration, even the .NET itself, in the old days we had to use the Web.config file to configure our Web Apps and today we do that stuff using the Startup file and using builders.

**Comment by Matthew-Davey** [comment]
It's simple to configure the cluster with a JSON file using the `Microsoft.Extensions.Configuration` family of packages (`Microsoft.Extensions.Configuration.Json` & `Microsoft.Extensions.Configuration.Binder`).

Modify the cluster setup like so:
```c#
hostBuilder.ConfigureServices(static (context, services) => {
    services.AddKafkaFlowHostedService(kafka => {
        kafka.AddCluster(cluster => {
            cluster.WithBrokers(context.Configuration.GetSection("kafka:brokers").Get<String[]>());
            cluster.WithSecurityInformation(security => {
                context.Configuration.GetSection("kafka:security").Bind(security);
            });
        });
    });
});
```

And use following JSON file (eg. `appsettings.json`), with whatever additional options you require:
```json
{
  "kafka": {
    "brokers": [
      "localhost:9191",
      "localhost:9192",
      "localhost:9193"
    ],
    "security": {
      "securityProtocol": "SaslSsl",
      "saslMechanism": "ScramSha512",
      "saslPassword": "admin-secret",
      "saslUsername": "admin"
    }
  }
}
```

There are drawbacks to doing things this way, so make your choice wisely.
