### ISSUE TITLE
Avro - Value cannot be null - empty headers

### ISSUE THREAD

**Issue by spriet2000** [Farfetch/kafka-flow#211]
Hello I have some problems setting up Avro with my topics. Not sure if the problem is in code.

I have debezium pointing to some cdc tables. 

I have copied the Avro files from the registry to my project and generated with avrogen the c#.

The avrò schema looks like..

  "type" : "record",
  "name" : "Value",
  "namespace" : "mssql_deployment.dbo.Products",

I follow the Avro example in this repo. And I get an error 'Value cannot be null. '

KafkaFlow: Error executing consumer | Data: {"Message":{"Key":"AxYGcA==","Value":"AAAAAAHgmbAxCEJReAARzYQLWkvbM5F4ASDRFNEMwODExLUVDRkEtNDUxMy1CNEEyLUM0NDQzRTUyRjI3NAIMRGlyZWN0AAAAAAxlAAAAElVuZGVmaW5lZBxJbnZlAMU2luZ2c3RtZW50RnJlZQBQMmJjMDQ3OTczZTVkMzAwYjE4NDZjMDhkZWMwMhbmsC1pL2zOzEwZTliZWRhNzllNgAAAAAAAAACSDRFNEMwODExLUVDRkEtNDUxMy1CNEEyLUM0NDQzRTUyRjI3NAAAAgpmYWxzZQ=="},"Topic":"mssql-deployment.dbo.Products","MessageKey":"AxYGcA==","ConsumerName":"avro-consumer"} | Exception: {"Type":"System.ArgumentNullException","Message":"Value cannot be null. (Parameter \u0027typeName\u0027)","StackTrace":"   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark\u0026 stackMark)\n   at System.Type.GetType(String typeName)\n   at ConsoleApp1.SampleMessageTypeResolver.OnConsume(IMessageContext context) in /Users/rene/RiderProjects/ConsoleApp1/ConsoleApp1/SampleMessageTypeResolver.cs:line 22\n   at KafkaFlow.SerializerConsumerMiddleware.Invoke(IMessageContext context, MiddlewareDelegate next)\n   at KafkaFlow.Consumers.ConsumerWorker.\u003CStartAsync\u003Eb__14_0()"}

_A type resolver is needed to instruct the middleware where to find the destination message type in the message metadata when consuming and where to store it when producing._ 

I have implemented a custom type resolver 'SampleMessageTypeResolver.cs' to debug further and found out the headers are empty.

`var typeName = context.Headers.GetString(MessageType);`

What should be the case here? if value is null its not possible to map the message to the serializer I guess. Message type where is it coming from?

I run Kafka 2.8.0

The code is pretty straight forward. I am only consuming messages from topic atm.

`var services = new ServiceCollection();
            
            const string topicName = "mssql-deployment.dbo.Products";
            const string consumerName = "avro-consumer";
            const string groupId = "avro-group-id17";

            services.AddKafka(
                kafka => kafka
                    .UseConsoleLog()
                    .AddCluster(
                        cluster => cluster
                            .WithBrokers(new[] { "192.168.1.48:32150" })
                            .WithSchemaRegistry(config => config.Url = "http://192.168.1.48:32250")
                            .AddConsumer(
                                consumer => consumer
                                    .Topic(topicName)
                                    .WithGroupId(groupId)
                                    .WithName(consumerName)
                                    .WithBufferSize(100)
                                    .WithWorkersCount(20)
                                    .WithAutoOffsetReset(AutoOffsetReset.Latest)
                                    .AddMiddlewares(
                                        middlewares => middlewares
                                            .AddSerializer<ConfluentAvroSerializer, SampleMessageTypeResolver>()
                                            .AddTypedHandlers(
                                                handlers => handlers
                                                    .WithHandlerLifetime(InstanceLifetime.Singleton)
                                                    .AddHandler<ProductsHandler>())
                                    )
                            )
                    )
            );
            
            var provider = services.BuildServiceProvider();

            var bus = provider.CreateKafkaBus();

            await bus.StartAsync();
            
            var consumers = provider.GetRequiredService<IConsumerAccessor>();

            while (true)
            {
                var input = Console.ReadLine().ToLower();
                switch (input)
                {
                    case "exit":
                        await bus.StopAsync();
                        return;
                }
                
            }`

**Comment by jplumhoff** [comment]
Hi @spriet2000 - I'm just learning Kafka-Flow myself, so I could be way off... but I think the MessageType header is generated by the DefaultMessageTypeResolver when Kafka-Flow is used to produce a message (see [the wiki section on message resolvers](https://github.com/Farfetch/kafka-flow/wiki/Serializer-Middleware#message-type-resolver)).  If your messages are coming from a non-Kafka-Flow producer, you'll either have to find a way for it to add a "MessageType":"yourMessageClass" key/value pair in the header from the producer side, or write your own MessageTypeResolver and configure it into your Kafka-Flow consumer so it can resolve the class based on information that is already present in the message.

**Comment by spriet2000** [comment]
Ok I misunderstood this part. I thought this was a Kafka client, not a framework. I have not control over all producers in our system. I will check this out further or investigate a different library. 

I don't believe it's required to rely on custom headers to find out the type when a registry is in place. 

Thanks

**Comment by jplumhoff** [comment]
No problem, and I hope you're right about the registry not needing custom headers.  I'm very new to Kafka-Flow (and Kafka in general) so I may just be missing something obvious.  Hopefully one of the project maintainers can help clarify this.  And I'm actually working on some test apps over the next few days that would use the registry - if I figure anything relevant out, I'll post back here.

**Comment by filipeesch** [comment]
> Ok I misunderstood this part. I thought this was a Kafka client, not a framework.
> 
> 'KafkaFlow is a .NET framework' :-) I found that out quickly
> 
> I have not control over all producers in our system. I will check this out further or investigate a different library.
> 
> I don't believe it's required to rely on custom headers to find out the type when a registry is in place.
> 
> Thanks

Hi @spriet2000. This header is just needed when you are using a topic with multiple message types, when a topic has just one message type you can set the message type in the setup process. Look at [here ](https://github.com/Farfetch/kafka-flow/wiki/serializer-middleware), you can use the `AddSingleTypeSerializer `for that

**Comment by spriet2000** [comment]
Thanks @filipeesch  and @jplumhoff. Will try the solution.
