### ISSUE TITLE
BatchConsume is broken in version >= 2.1.4

### ISSUE THREAD

**Issue by Liklainy** [Farfetch/kafka-flow#225]
There is a problem with `BatchConsume` after adding middleware instance lifetimes.
Middleware after `BatchConsumeMiddleware` is instantiated with disposed scope when postponed `next` is dispatched.

**Steps to reproduce:**
1. Run `KafkaFlow.Sample.BatchConsume` sample project
2. Send message and wait 10 seconds

**Exception message:**

> System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'IServiceProvider'.'

**Comment by filipeesch** [comment]
Hi @Liklainy thanks for your feedback, we will release a fix soon.
