### ISSUE TITLE
ClientDisposed error when using kafka-flow with schema registry in hosted service

### ISSUE THREAD

**Issue by guidowalter** [Farfetch/kafka-flow#230]
Hi,
hope someone can help us with a strange error we get, when using kafka-flow in a hosted service:

- We have two separate services in two different projects in two docker containers (.net core 5). Both services are hosted services:

Service 1:
```
// Add KAFKA Producers and Consumers
                    services.AddKafkaFlowHostedService(kafka => kafka
                      .UseConsoleLog()                      
                      .AddCluster(cluster => cluster
                          .WithBrokers(new[] { "<URL removed>:9092" })                         
                          .WithSchemaRegistry(config => config.Url = "<URL removed>:8081")                          
                          .AddConsumer(consumer => consumer
                              .Topic("tenant-management")
                              .WithGroupId("keycloak-handler")
                              .WithBufferSize(100)
                              .WithWorkersCount(10)                              
                              .WithAutoOffsetReset(AutoOffsetReset.Earliest)
                              .AddMiddlewares(middlewares => middlewares
                                  .AddSchemaRegistryAvroSerializer()                                  
                                  .AddTypedHandlers(
                                                  handlers => handlers
                                                      .AddHandler<CreateTenantRequestHandler>()
                                                      )
                              )
                          )
                          .AddProducer("tenant-management-keycloak", producer => producer
                                              .DefaultTopic("tenant-management")
                                              .AddMiddlewares(middlewares => middlewares
                                                      .AddSchemaRegistryAvroSerializer(
                                                          new AvroSerializerConfig
                                                          {
                                                              SubjectNameStrategy = SubjectNameStrategy.TopicRecord
                                                          }))
                                  )
                      ));
                })
```

Service2:

```
// Add KAFKA Producers and Consumers
                    services.AddKafkaFlowHostedService(kafka => kafka
                      .UseConsoleLog()
                      .AddCluster(cluster => cluster
                          .WithBrokers(new[] { "<URLremoved>:9092" })
                          .WithSchemaRegistry(config => config.Url = "<URLremoved>:8081")
                          .AddConsumer(consumer => consumer
                                  .Topic("tenant-management")
                                  .WithGroupId("kong-handler")
                                  .WithBufferSize(100)
                                  .WithWorkersCount(10)
                                  .WithAutoOffsetReset(AutoOffsetReset.Earliest)
                                  .AddMiddlewares(middlewares => middlewares
                                    .AddSchemaRegistryAvroSerializer()
                                    .AddTypedHandlers(
                                                   handlers => handlers
                                                       .AddHandler<CreateKongCredentialsRequestHandler>()
                                                       )
                                   )
                          )
                      ));
```

The basic flow is as follows:

Service 1 reads message in topic with schema -> calls handler -> produces new message in same topic with other schema 
Service 2 reads message in topic with new schema 

Service 1 always works - we can invoke the service multiple times and it does everything is has to do.
Service 2 always crashes with the following error message:

`Exception: {"Type":"System.ObjectDisposedException","Message":"Cannot access a disposed object.\r\nObject name: \u0027System.Net.Http.HttpClient\u0027.","StackTrace":" at System.Net.Http.HttpClient.CheckDisposed()\r\n at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)\r\n at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func\u00601 createRequest)\r\n at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)\r\n at Confluent.SchemaRegistry.RestService.GetSchemaAsync(Int32 id, String format)\r\n at Confluent.SchemaRegistry.CachedSchemaRegistryClient.GetSchemaAsync(Int32 id, String format)\r\n at KafkaFlow.ConfluentAvroTypeNameResolver.Resolve(Int32 id)\r\n at KafkaFlow.SchemaRegistryTypeResolver.\u003COnConsume\u003Eb__3_0(Int32 id)\r\n at System.Collections.Concurrent.ConcurrentDictionary\u00602.GetOrAdd(TKey key, Func\u00602 valueFactory)\r\n at KafkaFlow.SchemaRegistryTypeResolver.OnConsume(IMessageContext context)\r\n at KafkaFlow.SerializerConsumerMiddleware.Invoke(IMessageContext context, MiddlewareDelegate next)\r\n at KafkaFlow.Consumers.ConsumerWorker.\u003CStartAsync\u003Eb__14_0()"}`

We investigates this as far as we could and found out, that the RestService in the kafkfa .net client generates a list of schema URLs with references to the used httpClient. If we use the Restservice itself and separate from kafka-flow, it works multiple times.
In kafka-flow the error occurs even if we combine the two service into one (with two handlers). 
But if we only use the second service by generating the message by hand, it works as well.

What we also saw is that different scope types are used in the whole DI 'chain': 
kafka-flow uses a transcient scope for the hosted service, kfka.net uses a singelton scope for the rest service,...

Any help is appreciated as we totally ran out of ideas.
Thanks!

**Comment by dougolima** [comment]
Hi @guidowalter, are you using

**Comment by jplumhoff** [comment]
I saw the same problem in v2.1.11, and now in v2.1.13 with a service that sends 2 different protobuf messages to the same topic.  When the second message arrives, it errors out during deserialization and produces the same stacktrace @guidowalter saw.  It is easy to reproduce - just have a program send two different messages to the same topic and try to consume them both.  The first one will be consumed and handled correctly, the second one always fails.

**Comment by dougolima** [comment]
Hi @guidowalter and @jplumhoff, thanks for the issue.

We are investigating it and soon a new version fixing it will be released.

**Comment by guidowalter** [comment]
@jplumhoff  and @dougolima Thanks for your help!!
