### ISSUE TITLE
Kafka-flow and Confluent.Kafka version 1.8.2

### ISSUE THREAD

**Issue by i-arge** [Farfetch/kafka-flow#247]
Hi,

is it possible to know the kafka-flow release with dependency to Confluent.Kafka 1.8.2?
We ask this because we need to use the following configuration to be able to handle multiple events in the same topic (https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/):

```
// Producer configuration
.AddMiddlewares(middlewares => middlewares
	.AddSerializer(
		resolver => new ConfluentProtobufSerializer(
			resolver,
			new ProtobufSerializerConfig 
			{
				AutoRegisterSchemas = false,
				UseLatestVersion = true // New property in Confluent.Kafka 1.8.2
			}
		)
	)
)
```

Thank you very much,
Ivan

**Comment by filipeesch** [comment]
Hi @i-arge 
You can update the Confluent packages independently, as far that does not have any breaking change from them.
