### ISSUE TITLE
Make KafkaFlow.ConfluentAvroTypeNameResolver public

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [Farfetch/kafka-flow#250]
Hello, 

I am trying to use different approach to Avro + Schema Registry serialization.
I.e. [this library](https://github.com/ch-robinson/dotnet-avro/tree/main/src/Chr.Avro.Confluent)

So I've implemented `KafkaFlow.ISerializer` and inside this implementation I am using Chr.Avro.Confluent class.
I was able to register using `AddSerializer` and everything works both for producing and consuming.

Just one small issue is that I can't use `KafkaFlow.ConfluentAvroTypeNameResolver` in `AddSerializer` method, because class is `internal`.

Currently I just copied the class code to my sources and using it when calling `AddSerializer`

```
...

.AddProducer<MyObject>(p => p.DefaultTopic("my_topic_chr")
    .AddMiddlewares(m => m.AddSerializer(
        resolver => new ChrAvroSerializer(resolver.Resolve<ISchemaRegistryClient>()),
        resolver => new SchemaRegistryTypeResolver(new ChrAvroTypeNameResolver(resolver.Resolve<ISchemaRegistryClient>()))
    ))
)
```
where `ChrAvroSerializer` is my implementation of `ISerializer` and `ChrAvroTypeNameResolver` is a copy of `KafkaFlow.ConfluentAvroTypeNameResolver`

So, it would be great if you can make `KafkaFlow.ConfluentAvroTypeNameResolver` public, so the code can be reused when someone wants to use different serialization approaches while working with confluent compatible schema registries.

**Comment by ievgenii-shepeliuk** [comment]
If it's OK - I can provide a small PR for this :)

**Comment by filipeesch** [comment]
Hi @ievgenii-shepeliuk ,

Sometime we prefer to leave some classes as internal or sealed to avoid breaking changes on client, we don't know how this classes will evolve. What we do here is give to the clients the possibility to extend the framework behavior using interfaces, as you did, some time is just a copy paste with some changes.

**Comment by ievgenii-shepeliuk** [comment]
@filipeesch ok, but ... what does this response mean for the issue ?

is it so hard to give straight answer? As, yes we will implement or no, we will not implement ?

**Comment by filipeesch** [comment]
We will not implement for the reasons I already said.

**Comment by ievgenii-shepeliuk** [comment]
Fair enough. Thanks for the reply.
