### ISSUE TITLE
[question] LogHandler implementation based on Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [Farfetch/kafka-flow#253]
Hi, KafkaFlow deps

Are you interested in a contribution of `ILogHandler` implementation based on [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0) ?

**Comment by filipeesch** [comment]
Yes, it would be nice.

**Comment by ievgenii-shepeliuk** [comment]
Sorry, I am still working on the implementation of this.

**Comment by ievgenii-shepeliuk** [comment]
@filipeesch created PR #258
