### ISSUE TITLE
Offsets are committed after handler's failure

### ISSUE THREAD

**Issue by AlexeyRaga** [Farfetch/kafka-flow#283]
When I configure `KafkaFlow` with typed handlers, and the handler fails with an exception, the exception message is printed in logs, but the offsets are still committed. 

Is it a bug? Or what would be the way of making the consumer to stop and do not proceed further?

**Comment by AlexeyRaga** [comment]
Hi @filipeesch, how should the client application be handling this? By writing a middleware? Or there exist one that I haven't found yet?

**Comment by filipeesch** [comment]
Writing a middleware could be a solution, this is how I handle exceptions on my projects. If retry is a solution for you, there is another project at Farfetch that handles retries it: https://github.com/Farfetch/kafka-flow-retry-extensions

**Comment by AlexeyRaga** [comment]
Having retries is nice, but there are situations where messages cannot be handled because there is simply a bug in the handler, or if there is a long term outage / breaking API in 3rd party deps, etc. Things like "it won't be fixed until you deploy a newer version"...

I think that I just expected the default behaviour to be the safest one (stop the world, crash, don't commit offsets) and everything else would be opt-in. Which is not the case, as I now see.

I'll have a look at how to write a middleware and what can be done in it, thanks for the advice!

**Comment by filipeesch** [comment]
In most cases, we just stop the consumer and stay retrying forever (using a progressive interval), until the problem is over. This retry extension allows doing this :)

**Comment by AlexeyRaga** [comment]
@filipeesch thanks for all your help! Will investigate this option.
