### ISSUE TITLE
ProtobufMessageSerializer can't serialize a class generated using a file .proto 

### ISSUE THREAD

**Issue by felipelino** [Farfetch/kafka-flow#73]
## Issue Report

When you try to Serialize a class generated using a .proto file the `ProtobufMessageSerializer` throw an Exception `System.InvalidOperationException
Type is not expected, and no contract can be inferred: ...`

The Current Serializer appears to work only for .Net classes decorated with attributes `DataContract` , `DataMember`

## Expected Behavior

Should be able to Serialize a class generated using a proto file.
A reference here: https://developers.google.com/protocol-buffers/docs/csharptutorial#parsing_and_serialization

## Actual Behavior

When you try to Serialize a class generated using a .proto file the `ProtobufMessageSerializer` throws an Exception `System.InvalidOperationException
Type is not expected, and no contract can be inferred: ...`

## Steps to Reproduce the Issue

* Design a simple Protobuf file (from the Protobuf documentation)

`message Person {
  string name = 1;
  int32 id = 2;  // Unique ID number for this person.
  string email = 3;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
  }

  repeated PhoneNumber phones = 4;

  google.protobuf.Timestamp last_updated = 5;
}

// Our address book file is just one of these.
message AddressBook {
  repeated Person people = 1;
}`

* Generate classes 

`protoc -I=$SRC_DIR --csharp_out=$DST_DIR $SRC_DIR/addressbook.proto`

* Create a test

`
Person msg = new Person
{
    Id = 1234,
    Name = "John Doe",
    Email = "jdoe@example.com",
    Phones = { new Person.Types.PhoneNumber { Number = "555-4321", Type = Person.Types.PhoneType.Home } }
};

 var serializer = new ProtobufMessageSerializer();
 var byteArray1 = serializer.Serialize(msg ); // An Exception ara going to happen here
`

**Comment by felipelino** [comment]
What I did to solve:

`
using Google.Protobuf;
    using KafkaFlow.Serializer.ProtoBuf;
    using System;
    
    public class CustomProtobufMessageSerializer : ProtobufMessageSerializer
    {
        public byte[] Serialize(object message)
        {
            if (message is IMessage)
            {
                IMessage protoMsg = (IMessage) message;
                return protoMsg.ToByteArray();
            }

            return base.Serialize(message);
        }
        
        public object Deserialize(byte[] data, Type type)
        {
            if(typeof(IMessage).IsAssignableFrom(type))
            {
                IMessage instance =(IMessage) Activator.CreateInstance(type);
                instance.MergeFrom(data);
                return instance;
            }

            return base.Deserialize(data, type);
        }
    }
`

**Comment by filipeesch** [comment]
Hi Felipe, the profobuf serializer that we support is the commonly used [protobuf-net](https://github.com/protobuf-net/protobuf-net). To use protofile with it you should use the [protogen tool](https://github.com/protobuf-net/protobuf-net#proto-file). You can use another serializer too, but you should create a custom serializer middleware.

Thanks ;)

**Comment by ricsiLT** [comment]
Hi, sorry for necroposting but - why wasn't google library support merged back then? That library is defacto standard now, would it be worth revisiting?
