### ISSUE TITLE
question: middleware dependency lifetime

### ISSUE THREAD

**Issue by andrefilipegsilva** [Farfetch/kafka-flow#99]
Hi guys,

Is it possible to have middleware instances with a scoped or transient dependency lifetime? I've seen that the typed handlers framework allows for dependency lifetime customization, but I haven't found the same option for middleware.

To justify the need, I want to have a scoped instance that holds some management properties about the current consumption flow, but I want it to be as generic as possible, therefore I'd rather use middleware than typed handlers.

Regards.

**Comment by filipeesch** [comment]
Hi André,

The middlewares instances are configured in the DI container as transient, but we instantiate just one time for each consumer/producers, so, each consumer/producer has its own middleware instance, it behaves like scoped for the consumer/producer. 

For example, if you have two consumers with the same middleware, each consumer will have its own instance for the entire app lifetime. 

Side note: the instances are not shared between consumers, but is shared between consumer workers.

**Comment by andrefilipegsilva** [comment]
I see, that's what I thought after analyzing the middleware executor class. Still, would it be possible to support custom lifetimes for middleware instances?

**Comment by filipeesch** [comment]
We have no intention to change it for now. But you can inject your class instance in your custom middleware, as the middleware is "scoped" your class instance will be scoped too.

**Comment by andrefilipegsilva** [comment]
I've just tested this. I've done as you said, and injected my class instance, which had been registered as scoped, in my middleware.

I have used two consumption workers. The middleware ctor was called twice. After that, the middleware instance was always the same for all received messages.

As you said [here ](https://github.com/Farfetch/kafka-flow/issues/99#issuecomment-726183191) and according to [this](https://github.com/Farfetch/kafka-flow/blob/2faab89fc9011bdf773672d59a6dd4b452a55bc5/src/KafkaFlow/KafkaBus.cs#L43) line, middleware are created once per consumer and reused across all messages received. The behavior I am looking for is having these middleware created per message received (a truly scoped service lifetime).

**Comment by filipeesch** [comment]
Scoped behaviour can vary depending on the implementation. In this case, if we create a middleware instance for each received message I think it is more like a transient behaviour.

In your use case, you can apply your logic inside de Invoke() method. If you need an instance of a class of yours, you can create a factory class, inject in the middleware constructor and inside the Invoke() call your factory to create your instance (you can do that injecting the IServiceProdiver in the middleware too).

**Comment by andrefilipegsilva** [comment]
> Scoped behaviour can vary depending on the implementation. In this case, if we create a middleware instance for each received message I think it is more like a transient behaviour.

I don't think so. Think HTTP requests on ASP.NET, you can have scoped dependencies, which are reused per request, and then you can have transient dependencies that are always different, even if you retrieve the dependency more than once per request.

I believe we're talking about two types of scopes here: the _consumer scope_ and the _message scope_. I'm talking about the latter.

> In your use case, you can apply your logic inside de Invoke() method. If you need an instance of a class of yours, you can create a factory class, inject in the middleware constructor and inside the Invoke() call your factory to create your instance (you can do that injecting the IServiceProdiver in the middleware too).

I just tried it and it didn't work. The explanation for this could be that since the scope is always the same throughout the consumer lifetime, the returned instance is always the same.

**Comment by filipeesch** [comment]
> I just tried it and it didn't work. The explanation for this could be that since the scope is always the same throughout the consumer lifetime, the returned instance is always the same.

Could you post here how did you tried? Because it is supposed to work.

**Comment by andrefilipegsilva** [comment]
Sure. So I have a class that implements `ÌMessageMiddleware`:

```code csharp
public class OperationContextEvaluator : IMessageMiddleware
    {
        private readonly OperationContext operationContext;

        public OperationContextEvaluator(IServiceProvider serviceProvider)
        {
            this.serviceProvider = serviceProvider;
        }

        public async Task Invoke(IMessageContext messageContext, MiddlewareDelegate next)
        {
            var ctx = this.serviceProvider.GetService<OperationContext>();
            // (...)
         }
    }
}

```

_ctx_ is the same object for all incoming message flows.

Let me know if you need anything else

**Comment by filipeesch** [comment]
In this case, you must configure your OperationContext as transient or you create an inner scope inside Invoke().

**Comment by andrefilipegsilva** [comment]
My `OperationContext` is declared as Scoped. If I declare it as transient, on a downstream middleware the resolved instance will be different and I want it to remain the same across the same message flow.

According to your example, the `scope` will only live within that method, and thus if I want to share scoped instances I would need to pass that scope onto downstream middleware to be able to resolve the same instance there.

**Comment by filipeesch** [comment]
This behaviour is to avoid many object instances creation and to allow a middleware control the message flow inside a consumer. Handling the DI scope as ASP .NET does, can affect app performance due to the amount of objects creation and more work for  Garbage Collector.

Maybe if you use the Typed Handler will work for your case (you can implement your custom "typed handler" middleware with a custom behaviour). There, every message is executed inside a scope, so, if you have scoped instances it will be scoped for that message execution.
